In [1]:
# We have to import 
# from sklearn.experimental import enable_iterative_imputer
# first before importing IterativeImputer

In [2]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [3]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9) #to get same sample every time
df = df.sample(5)

In [4]:
df.reset_index(drop=True, inplace=True)
df

   R&D Spend  Administration  Marketing Spend  Profit
0        8.0            15.0             30.0    11.0
1        4.0             5.0             20.0     9.0
2       15.0            10.0             41.0    19.0
3       12.0            16.0             26.0    13.0
4        2.0            15.0              3.0     7.0

In [5]:
#Lets add missing values
df.iloc[0, 0] = np.nan
df.iloc[3, 1] = np.nan
df.iloc[4, 2] = np.nan

In [6]:
X = df.iloc[:, :-1]
X

   R&D Spend  Administration  Marketing Spend
0        NaN            15.0             30.0
1        4.0             5.0             20.0
2       15.0            10.0             41.0
3       12.0             NaN             26.0
4        2.0            15.0              NaN

In [7]:
y = df.iloc[:, 3:]
y

   Profit
0    11.0
1     9.0
2    19.0
3    13.0
4     7.0

In [8]:
ii = IterativeImputer()

In [9]:
imputed = ii.fit_transform(X)

In [10]:
df1 = pd.DataFrame(imputed, columns=X.columns)

In [11]:
df1

   R&D Spend  Administration  Marketing Spend
0   9.225443       15.000000        30.000000
1   4.000000        5.000000        20.000000
2  15.000000       10.000000        41.000000
3  12.000000       11.248927        26.000000
4   2.000000       15.000000        21.483372

In [13]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9) #to get same sample every time
df = df.sample(5)
df.reset_index(drop=True, inplace=True)
df

   R&D Spend  Administration  Marketing Spend  Profit
0        8.0            15.0             30.0    11.0
1        4.0             5.0             20.0     9.0
2       15.0            10.0             41.0    19.0
3       12.0            16.0             26.0    13.0
4        2.0            15.0              3.0     7.0

In [14]:
df.iloc[:,:-1]-df1

   R&D Spend  Administration  Marketing Spend
0  -1.225443        0.000000         0.000000
1   0.000000        0.000000         0.000000
2   0.000000        0.000000         0.000000
3   0.000000        4.751073         0.000000
4   0.000000        0.000000       -18.483372