In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('play_tennis.csv')

In [5]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [6]:
df = df.drop(columns='day')

In [7]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

# Manual

In [11]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [12]:
Pyes = 9/14
Pno = 5/14

In [14]:
pd.crosstab(df['outlook'], df['play'], margins=True)

play      No  Yes  All
outlook
Overcast   0    4    4
Rain       2    3    5
Sunny      3    2    5
All        5    9   14

In [18]:
POvercastNo = 0/5
PRainyNo = 2/5
PSunnyNo = 3/5
POvercastYes = 4/9
PRainyYes = 3/9
PSunnyYes = 2/9

In [17]:
pd.crosstab(df['temp'], df['play'], margins=True)

play  No  Yes  All
temp
Cool   1    3    4
Hot    2    2    4
Mild   2    4    6
All    5    9   14

In [19]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5
PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [20]:
pd.crosstab(df['humidity'], df['play'], margins=True)

play      No  Yes  All
humidity
High       4    3    7
Normal     1    6    7
All        5    9   14

In [21]:
PHighNo = 4/5
PNormalNo = 1/5
PHighYes = 3/9
PNormalYes = 6/9

In [22]:
pd.crosstab(df['wind'], df['play'], margins=True)

play    No  Yes  All
wind
Strong   3    3    6
Weak     2    6    8
All      5    9   14

In [23]:
PStrongNo = 3/5
PWeakNo = 2/5
PStrongYes = 3/9
PWeakYes = 6/9

### Prediction for `Overcast, Hot, Normal, Weak`

In [25]:
yes = Pyes*POvercastYes*PHotYes*PNormalYes*PWeakYes
no = Pno*POvercastNo*PHotNo*PNormalNo*PWeakNo

In [27]:
yes, no

(0.02821869488536155, 0.0)

In [26]:
print("Play" if yes>no else "No")

Play

# sklearn

In [38]:
X = df.drop(columns='play')
y = df['play']

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [39]:
labelencode = LabelEncoder()
y_encoded = labelencode.fit_transform(y)

In [41]:
categorical_col = ['outlook', 'temp', 'humidity', 'wind']

In [42]:
preprocessor = ColumnTransformer(transformers=[
    ('categorical', OrdinalEncoder(), categorical_col)
])

In [43]:
pipeline = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('model', CategoricalNB())
])

In [44]:
pipeline.fit(X, y)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('categorical',
                                                  OrdinalEncoder(),
                                                  ['outlook', 'temp',
                                                   'humidity', 'wind'])])),
                ('model', CategoricalNB())])

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y, pipeline.predict(X))

0.9285714285714286

### There are multiple algorithms out there for different type of data
BernoulliNB, CategoricalNB, ComplementNB, GaussianNB and MultinomialNB  
Each used for different type of features.

Naive bayes cant handle Mixed data (numeric, categorical and text).  
For it we learn RandomForest and XGBoost in future