In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
df.drop(columns=['age', 'gender'], inplace=True)

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Ordinal Encoding

In [7]:
df.review.unique()

<StringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str

In [14]:
df.education.unique()

<StringArray>
['School', 'UG', 'PG']
Length: 3, dtype: str

In [15]:
review_map = {
    'Poor' : 0,
    'Average' : 1,
    'Good': 2
}
edu_map = {
    'School' : 0,
    'UG' : 1,
    'PG': 2
}

In [16]:
df['review-encoded'] = df['review'].map(review_map)
df['edu-encoded'] = df['education'].map(edu_map)

In [17]:
df

     review education purchased  review-encoded  edu-encoded
0   Average    School        No               1            0
1      Poor        UG        No               0            1
2      Good        PG        No               2            2
3      Good        PG        No               2            2
4   Average        UG        No               1            1
5   Average    School       Yes               1            0
6      Good    School        No               2            0
7      Poor    School       Yes               0            0
8   Average        UG        No               1            1
9      Good        UG       Yes               2            1
10     Good        UG       Yes               2            1
11     Good        UG       Yes               2            1
12     Poor    School        No               0            0
13  Average    School        No               1            0
14     Poor        PG       Yes               0            2
15     Poor        UG        No               0            1
16     Poor        UG       Yes               0            1
17     Poor        UG       Yes               0            1
18     Good    School        No               2            0
19     Poor        PG       Yes               0            2
20  Average    School       Yes               1            0
21  Average        PG        No               1            2
22     Poor        PG       Yes               0            2
23     Good    School        No               2            0
24  Average        PG       Yes               1            2
25     Good    School        No               2            0
26     Poor        PG        No               0            2
27     Poor        PG        No               0            2
28     Poor    School        No               0            0
29  Average        UG       Yes               1            1
30  Average        UG        No               1            1
31     Poor    School       Yes               0            0
32  Average        UG       Yes               1            1
33     Good        PG       Yes               2            2
34  Average    School        No               1            0
35     Poor    School       Yes               0            0
36     Good        UG       Yes               2            1
37  Average        PG       Yes               1            2
38     Good    School        No               2            0
39     Poor        PG        No               0            2
40     Good    School        No               2            0
41     Good        PG       Yes               2            2
42     Good        PG       Yes               2            2
43     Poor        PG        No               0            2
44  Average        UG        No               1            1
45     Poor        PG       Yes               0            2
46     Poor        PG        No               0            2
47     Good        PG       Yes               2            2
48     Good        UG       Yes               2            1
49     Good        UG        No               2            1

# Label Encoding

Dont know what is the main difference between ordinal and label encoding while appling it from scratch!!.

In [21]:
purches = df['purchased'].unique()

In [22]:
purches_map = {p:i for i, p in enumerate(purches)}

In [24]:
df['purchesed_encoded']=df['purchased'].map(purches_map)

In [25]:
df

,review,education,purchased,review-encoded,edu-encoded,purchesed_encoded
0,Average,School,No,1,0,0
1,Poor,UG,No,0,1,0
2,Good,PG,No,2,2,0
3,Good,PG,No,2,2,0
4,Average,UG,No,1,1,0
5,Average,School,Yes,1,0,1
6,Good,School,No,2,0,0
7,Poor,School,Yes,0,0,1
8,Average,UG,No,1,1,0
9,Good,UG,Yes,2,1,1
10,Good,UG,Yes,2,1,1
11,Good,UG,Yes,2,1,1
12,Poor,School,No,0,0,0
13,Average,School,No,1,0,0
14,Poor,PG,Yes,0,2,1
15,Poor,UG,No,0,1,0
16,Poor,UG,Yes,0,1,1
17,Poor,UG,Yes,0,1,1
18,Good,School,No,2,0,0
19,Poor,PG,Yes,0,2,1
20,Average,School,Yes,1,0,1
21,Average,PG,No,1,2,0
22,Poor,PG,Yes,0,2,1
23,Good,School,No,2,0,0
24,Average,PG,Yes,1,2,1
25,Good,School,No,2,0,0
26,Poor,PG,No,0,2,0
27,Poor,PG,No,0,2,0
28,Poor,School,No,0,0,0
29,Average,UG,Yes,1,1,1
30,Average,UG,No,1,1,0
31,Poor,School,Yes,0,0,1
32,Average,UG,Yes,1,1,1
33,Good,PG,Yes,2,2,1
34,Average,School,No,1,0,0
35,Poor,School,Yes,0,0,1
36,Good,UG,Yes,2,1,1
37,Average,PG,Yes,1,2,1
38,Good,School,No,2,0,0
39,Poor,PG,No,0,2,0
40,Good,School,No,2,0,0
41,Good,PG,Yes,2,2,1
42,Good,PG,Yes,2,2,1
43,Poor,PG,No,0,2,0
44,Average,UG,No,1,1,0
45,Poor,PG,Yes,0,2,1
46,Poor,PG,No,0,2,0
47,Good,PG,Yes,2,2,1
48,Good,UG,Yes,2,1,1
49,Good,UG,No,2,1,0

Here the `No` got `0` and `Yes` got `1`